services:
  # Backend service
  - type: web
    name: eims-demo-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: eims-demo-db
    #     property: connectionString
    # - key: SESSION_SECRET
    #   generateValue: true

  # Frontend service (static site)
  - type: static
    name: eims-demo-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

# Database (if needed)
# databases:
#   - name: eims-demo-db
#     plan: free
#     databaseName: eims_demo
#     user: eims_user
